spring:
  profiles:
    group:
      local:
        - local-mysql
        - local-token
        - local-image
      dev:
        - dev-mysql
        - dev-token
        - dev-image
      test:
        - test-mysql
        - test-token
        - test-image
    active: local
